apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pjbosv4vr-python 
  janus-idp.io/tekton: pjbosv4vr-python
  backstage.io/kubernetes-id: pjbosv4vr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pjbosv4vr-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  